### PR TITLE
before_install with node-gyp

### PR DESCRIPTION
**Pull request by odra**
do not merge

### CODE REVIEW

**Comment by matzew** [comment]
@odra @sebastienblanc does this mean we need an update of that library on the server (running the MBaaS) as well ?

**Comment by sebastienblanc** [comment]
@odra @matzew For 0.10.x this should not be needed, at least on the clusters it's deploying fine

**Comment by odra** [comment]
@sebastienblanc @matzew  It could already be installed for 0.10.x, it just needs to be installed for specific modules (usually the ones that compile stuff).

I can add a post install script do it only for node 4.x and test it again, what do you think?

**Comment by matzew** [comment]
👍

**Comment by sebastienblanc** [comment]
yeah ! Go for it !

**Pull request merged**
