### PR TITLE
📈 Instrument to track CPU/Mem usage & requests

### PR DESCRIPTION
**Pull request by grdryn**

### CODE REVIEW

**Comment by grdryn** [comment]
@david-martin @aidenkeating Would you like to review? I haven't included the forked version of fh-mbaas-api. Should I?

Also, is this something that is expected to get merged back, or not? In any case, I don't think I have the ability to merge since I'm not in this org.

**Comment by aidenkeating** [comment]
@grdryn Top notch! 👍  I haven't tested it though, but I am confident you have

I don't think it would hurt to include a forked version of fh-mbaas-api. It might give you insights into how sync factors in to raincatcher performance or something like that. If it doesn't, you can always remove it after. Although, probably not best to include it if you'll be merging these changes.

There are a lot of metrics forks and most have other changes, this has only the metrics changes `aidenkeating/fh-mbaas-api#add_method_time_monitoring`.

**Comment by david-martin** [comment]
@grdryn Since this is using the instrumented fork of fh-mbaas-api, lets not merge back.
If you want to cherry-pick the changes for metrics only, I see no reason that couldn't be merged back given its behind a boolean flag

**Comment by paolobueno** [comment]
:+1: on this being merged since not enabled by default. Might be good to add docs for users if it would be useful for them.

Else it would still be nice to push this to a branch in the original repo instead of keeping it in a personal fork.

@nialldonnellyfh might be interested as well.

**Comment by grdryn** [comment]
Yeah, the first two commits are probably mergeable, maybe not the 3rd one as @david-martin said. If @paolobueno and @nialldonnellyfh wish, I can open a separate PR for just those ones, and we can have that merged back?

I don't think I can add a branch to the origin repo for the rest, since I'm not a member of the feedhenry-raincatcher GitHub org.

**Comment by paolobueno** [comment]
pushed up the merged branch to upstream at [RAINCATCH-566](/feedhenry-raincatcher/raincatcher-demo-cloud/tree/RAINCATCH-566)

**Comment by grdryn** [comment]
@paolobueno ok, thanks. I'll close this PR in that case.

**Pull request closed without merging**
