### PR TITLE
RHMAP-8254 .travis.yml update

### PR DESCRIPTION
**Pull request by psturc**

### CODE REVIEW

**Comment by bleathem** [comment]
I'm not really cool with having this build script living in a random gist.  Can we put this somewhere official, and consider publishing it to npm for consumption in projects?

**Comment by matzew** [comment]
👍 that would be best

**Comment by matzew** [comment]
@psturc lets update this, using fh-build?

**Comment by psturc** [comment]
Merged in https://github.com/feedhenry-raincatcher/raincatcher-demo-cloud/pull/12

**Pull request closed without merging**
