### PR TITLE
Updating to 5.13.1

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by sebastienblanc** [comment]
@matzew I think npm-shrinkwrap needs to be updated as well ;)

**Comment by sebastienblanc** [comment]
@matzew If you rebase with master you should be able to generate the skrinkcrap with `rm -rf node_modules && npm cache clean && npm install --production && npm shrinkwrap`

**Comment by matzew** [comment]
@sebastienblanc of course, that does not work!

the npm "tool" just drives me nuts

**Comment by matzew** [comment]
@sebastienblanc @odra looks like the pre scripts are not Mac friendly ?

getting:
```
rm -rf node_modules/ && npm i --production && npm i fh-mbaas-api@5.13.1 && npm cache clean && npm shrinkwrap
npm WARN package.json fh-app@2.0.0-alpha.6 No repository field.

> fh-app@2.0.0-alpha.6 preinstall /Users/matzew/Work/FeedHenry/TEMPLATES/wfm-auth
> chmod +x scripts/preinstall.sh && scripts/preinstall.sh

npm ERR! code 1
```

**Comment by odra** [comment]
@matzew It could be an issue with npm (I was able to run it in my mac), could you please try to run the command ´npm install -g node-pre-gyp´?

Also, are you using node with nvm or did you install it with homebrew?

**Comment by matzew** [comment]
nvm --version
0.31.1

the `npm install -g node-pre-gyp` worked fine :-)

JOY! :)

On Fri, Jul 1, 2016 at 10:09 PM, Leonardo Rossetti <notifications@github.com
> wrote:

> @matzew <https://github.com/matzew> It could be an issue with npm (I was
> able to run it in my mac), could you please try to run the command ´npm
> install -g node-pre-gyp´?
>
> Also, are you using node with nvm or did you install it with homebrew?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/feedhenry-raincatcher/raincatcher-demo-cloud/pull/9#issuecomment-230036905>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAJnzjZR__opnBp43sbxZgkAV_4DlCYxks5qRXPggaJpZM4JC6Gs>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
twitter: http://twitter.com/mwessendorf

**Comment by matzew** [comment]
but, yeah... the my "rm -rf node_modules && npm cache clean && npm install
--production && npm shrinkwrap" continues to fail!

pure joy!

On Fri, Jul 1, 2016 at 11:01 PM, Matthias Wessendorf <matzew@apache.org>
wrote:

>  nvm --version
> 0.31.1
>
> the `npm install -g node-pre-gyp` worked fine :-)
>
> JOY! :)
>
> On Fri, Jul 1, 2016 at 10:09 PM, Leonardo Rossetti <
> notifications@github.com> wrote:
>
>> @matzew <https://github.com/matzew> It could be an issue with npm (I was
>> able to run it in my mac), could you please try to run the command ´npm
>> install -g node-pre-gyp´?
>>
>> Also, are you using node with nvm or did you install it with homebrew?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/feedhenry-raincatcher/raincatcher-demo-cloud/pull/9#issuecomment-230036905>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAJnzjZR__opnBp43sbxZgkAV_4DlCYxks5qRXPggaJpZM4JC6Gs>
>> .
>>
>
>
>
> --
> Matthias Wessendorf
>
> blog: http://matthiaswessendorf.wordpress.com/
> twitter: http://twitter.com/mwessendorf
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
twitter: http://twitter.com/mwessendorf

**Comment by odra** [comment]
@matzew You need to remove the shrinkwrap file before  generating a new one, so the correct command order would be:

`rm -rf node_modules && npm cache clean && rm npm-shrinkwrap.json && npm install --production && npm shrinkwrap`

**Comment by matzew** [comment]
Ok, updated this:
```
alias shrinkcrap='rm -rf node_modules && npm cache clean && rm npm-shrinkwrap.json && npm install --production && npm shrinkwrap'
```

😄 

thanks, @odra

**Pull request merged**
